apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database-service
spec:
  selector:
    app: database
  ports:
    - name: database-port
      port: 5432
      targetPort: 5432
  type: ClusterIP